-- Goal: Demonstrate how to create a table in SQL and fetch data from it.

CREATE TABLE STUDENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT,
    ADDRESS VARCHAR(100)
);

INSERT INTO STUDENT (ID, NAME, AGE, ADDRESS) VALUES (1, 'Ram', 18, 'Delhi');
INSERT INTO STUDENT (ID, NAME, AGE, ADDRESS) VALUES (2, 'Sujit', 19, 'Mumbai');
INSERT INTO STUDENT (ID, NAME, AGE, ADDRESS) VALUES (3, 'Priya', 18, 'Delhi');
INSERT INTO STUDENT (ID, NAME, AGE, ADDRESS) VALUES (4, 'Anita', 20, 'Kolkata');

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'Delhi';
SELECT * FROM STUDENT WHERE NAME = 'Ram' AND AGE = 18;
SELECT * FROM STUDENT WHERE NAME = 'Ram' OR NAME = 'Sujit';
