CREATE TABLE IF NOT EXISTS NOBEL_WIN (
    YEAR INTEGER,
    COUNTRY TEXT,
    SUBJECT TEXT,
    WINNER TEXT PRIMARY KEY,
    CATEGORY TEXT
);

INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
(1972, 'PHYSICS', 'LOUIS WELL', 'FRANCE', 'SCIENTIST'),
(1974, 'PHYSICS', 'PANA', 'FRANCE', 'SCIENTIST'),
(1971, 'CHEMISTRY', 'HOMILAND', 'SWEDEN', 'CHEMIST'),
(1972, 'LITERATURE', 'REMMOND RELSON', 'GERMANY', 'ECONOMIST'),
(1973, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
(1980, 'BIOLOGY', 'PHILIPS', 'USA', 'PEACE MINISTRY'),
(1994, 'BIOLOGY', 'PWEITA', 'USA', 'PRESIDENT'),
(1994, 'PHYSIOLOGY', 'MANAGEM', 'HUNGARY', 'SCIENTIST'),
(1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');


SELECT * FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';

SELECT * FROM NOBEL_WIN
ORDER BY YEAR DESC;